### PR TITLE
Add new custom props

### PR DESCRIPTION
**Pull request by hreyeslo**
I added new custom props to improve the customization of this powerfull  webcomponent.

### CODE REVIEW

**Comment by hreyeslo** [comment]
Sorry for the indentation, i did all in the browser and i couldn't check, if you want i can repeat and do better.

**Comment by Julien-Marcou** [comment]
Hi, thank you for you contribution.

Having the padding customizable independently for each scrollbar is a welcome feature, though I have a change to suggest. The way you have implemented it makes it a breaking change, as people who have used the `--scrollbar-padding` in their code will no longer have it working.

A fix could be to use the `--scrollbar-padding` as the default value for the `--horizontal-scrollbar-padding` & `--vertical-scrollbar-padding`:

```css
  --scrollbar-padding: 2px;
  --vertical-scrollbar-padding: var(--scrollbar-padding);
  --horizontal-scrollbar-padding: var(--scrollbar-padding);
```

That way it is no longer a breaking change and you can still override the padding for each scrollbar.

For the z-index properties, also I'm not against it, I have a hard time to undestand why you would change them,
even if you add absolute content inside the <scrollable-component> with a high z-index, it should already render correctly under the scrollbars, and for content outside of the <scrollable-component> you can use z-index directly on the component itself to place it over/under other absolute content.
Do you have a use case for this ?

**Comment by hreyeslo** [comment]
Hi, sorry for the dealy.

Your suggestion is totally right, so i'm going to update it.
The z-index properties, I suggested that because i'm trying to use in a big project with a lot of number of pieces with different layers and the 99% of pieces works perfectly but when i'm trying to use a material.io drawer inside this scroll-container, the scroll appear over this component.

Obviously, the firs think is... why you are using this component inside the scroll component? Ok, the reason is that we are using a proyect based on micro-frontends, and we  need to have a main wrapper to provide in a cross way this behaviour, so in the main container we can manage the content and the palces where we are putting the content, but when we load a micro-frontend, we need to load in a specific route and we loose the control of the content, and the peices in this point will be inside the scroll container and we can't do nothing. So for this reason, i suggested to  include a property to provide a capability to configure as i need it.

**Comment by Julien-Marcou** [comment]
I was writing you a new answer at the same moment 😅

I've been working on a new version (v1.2.0), which refactorize a lot of code, and I took the opportunity to add the new properties for the padding ^^

**Comment by hreyeslo** [comment]
Ohh it's sounds great!
I would appreciate a lot if you will take in consideration my suggestion about the props for configure the z-index values. Because, when i set on auto, all work perfectly, and ofc i know you configured with this values for a strong reason, but i think that this values  could be default and it's no matter to have 3 props to configure it as the developpers need.

What do you think about that?

**Comment by Julien-Marcou** [comment]
For the z-index, I don't think it will completely solve your problem, I mean yes, the scrollbars are designed to be on top of any content you put inside the viewport, but if you change the viewport's z-index, so it's on top of the scrollbars, then you won't be able to scroll using the scrollbars (the viewport will catch the mouse event before it has a chance to be triggered on the scrollbars themselves), and any non-transparent content will hide the scrollbars, may be this is what you want ?

**Comment by hreyeslo** [comment]
No, the problem is that i can't take control for each micro-frontend and the layers and contexts, so for that with auto works perfectly in all cases.

z-index : auto -> The box does not establish a new stacking context. The stacking level of the generated box is the same as that of the parent box.

So in my case is the best solution, because with this i don't need to know the contexts and the content that the apps have, but i cant configure that because i can't access to the shadow.

**Comment by Julien-Marcou** [comment]
Ah yes, I undestand, with `auto` it makes sense.

The z-index were originally added so the hovered scrollbar would be on top of the other one (this is and edge case when you have both scrollbar displayed at the same time and they are both in the bottom-right corner).

Can you open a new PR for the z-index ?

**Comment by hreyeslo** [comment]
Yes i'm going to do it :wink:

**Comment by Julien-Marcou** [comment]
Also, just so you know, I'll start working on a v2 after the release of the v1.2, it will be a breaking release, where I'll remove almost all of the CSS properties as I think it was a mistake to have so many in the first place, because if someone wants to customize a new CSS property I haven't provided in the first place, the property needs to be manually added every single time, and will slowly but surely make the component heavier and heavier (even though most of the people will never use most of the CSS properties).

When I started coding this component, the CSS `::part()` specs were quite new, and I didn't want to take the risk of them not being properly implemented on modern browsers, but this is not the case anymore, adding `::part()` will allow me to remove CSS properties to make the component even lighter and allow others to customize endlessly every parts of this component.

This would give you something like that:

```css
/* Before */
scrollable-component {
  --scrollbar-opacity: 0.5; /* not possible at the moment */
  --vertical-scrollbar-padding: 10px 2px;
  --horizontal-scrollbar-padding: 2px 10px;
}
```

```css
/* After */
scrollable-component::part(scrollbar) {
  opacity: 0.5;
}
scrollable-component::part(vertical-scrollbar) {
  padding: 10px 2px;
}
scrollable-component::part(horizontal-scrollbar) {
  padding: 2px 10px;
}
```

**Pull request closed without merging**
